"""Browser mockup shows a box that looks like a browser window."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/mockup/browser.ipynb.

# %% auto 0
__all__ = ['mockup_browser', 'mockup_browser_toolbar', 'test_mockup_browser_basic_examples']

# %% ../../../nbs/components/mockup/browser.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/mockup/browser.ipynb 5
mockup_browser = SingleValueFactory("mockup-browser", "Base browser mockup component") # Base mockup browser component
mockup_browser_toolbar = SingleValueFactory("mockup-browser-toolbar", "Toolbar part which can include addressbar, etc") # Base mockup browser toolbar part

# %% ../../../nbs/components/mockup/browser.ipynb 7
def test_mockup_browser_basic_examples():
    """Test basic mockup_browser utilities."""
    # Basic mockup_browser
    assert str(mockup_browser) == "mockup-browser"
    assert str(mockup_browser_toolbar) == "mockup-browser-toolbar"
    
    # Test with modifiers
    assert str(mockup_browser.hover) == "hover:mockup-browser"
    assert str(mockup_browser.md) == "md:mockup-browser"
    assert str(mockup_browser.dark) == "dark:mockup-browser"

# Run the tests
test_mockup_browser_basic_examples()
