"""Code mockup is used to show a block of code in a box that looks like a code editor."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/mockup/code.ipynb.

# %% auto 0
__all__ = ['mockup_code', 'test_mockup_code_basic_examples']

# %% ../../../nbs/components/mockup/code.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/mockup/code.ipynb 5
mockup_code = SingleValueFactory("mockup-code", "Base code terminal mockup") # Base mockup code component

# %% ../../../nbs/components/mockup/code.ipynb 7
def test_mockup_code_basic_examples():
    """Test basic mockup_code utilities."""
    # Basic mockup_code
    assert str(mockup_code) == "mockup-code"
    
    # Test with modifiers
    assert str(mockup_code.hover) == "hover:mockup-code"
    assert str(mockup_code.md) == "md:mockup-code"
    assert str(mockup_code.dark) == "dark:mockup-code"

# Run the tests
test_mockup_code_basic_examples()
