"""Phone mockup shows a mockup of an iPhone."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/mockup/phone.ipynb.

# %% auto 0
__all__ = ['mockup_phone', 'mockup_phone_camera', 'mockup_phone_display', 'test_mockup_phone_basic_examples']

# %% ../../../nbs/components/mockup/phone.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/mockup/phone.ipynb 5
mockup_phone = SingleValueFactory("mockup-phone", "Base phone mockup component") # Base mockup phone component
mockup_phone_camera = SingleValueFactory("mockup-phone-camera", "Camera part") # Mockup phone camera part
mockup_phone_display = SingleValueFactory("mockup-phone-display", "Display part") # Mockup phone display part

# %% ../../../nbs/components/mockup/phone.ipynb 7
def test_mockup_phone_basic_examples():
    """Test basic mockup_phone utilities."""
    # Basic mockup_phone
    assert str(mockup_phone) == "mockup-phone"
    assert str(mockup_phone_camera) == "mockup-phone-camera"
    assert str(mockup_phone_display) == "mockup-phone-display"
    
    # Test with modifiers
    assert str(mockup_phone.hover) == "hover:mockup-phone"
    assert str(mockup_phone.md) == "md:mockup-phone"
    assert str(mockup_phone.dark) == "dark:mockup-phone"

# Run the tests
test_mockup_phone_basic_examples()
