"""Window mockup shows a box that looks like an operating system window."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/mockup/window.ipynb.

# %% auto 0
__all__ = ['mockup_window', 'test_mockup_window_basic_examples']

# %% ../../../nbs/components/mockup/window.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/mockup/window.ipynb 5
mockup_window = SingleValueFactory("mockup-window", "Base OS window mockup") # Base mockup window component

# %% ../../../nbs/components/mockup/window.ipynb 7
def test_mockup_window_basic_examples():
    """Test basic mockup_window utilities."""
    # Basic mockup_window
    assert str(mockup_window) == "mockup-window"
    
    # Test with modifiers
    assert str(mockup_window.hover) == "hover:mockup-window"
    assert str(mockup_window.md) == "md:mockup-window"
    assert str(mockup_window.dark) == "dark:mockup-window"

# Run the tests
test_mockup_window_basic_examples()
