"""Window mockup shows a box that looks like an operating system window."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/mockup/mockup_window.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/mockup/mockup_window.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
