"""Named sizes support for DaisyUI components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/builders/sizes.ipynb.

# %% auto #0
__all__ = ['DaisyUINamedSize']

# %% ../../nbs/builders/sizes.ipynb #d623facf-9df1-4c99-83ad-5f1bddf5b1a4
from enum import Enum

# %% ../../nbs/builders/sizes.ipynb #c68bbfdc-4b73-4a94-9e5a-6f567da4b7c9
# DaisyUI names sizes
class DaisyUINamedSize(str, Enum):
    XS = "xs"
    SM = "sm"
    MD = "md"
    LG = "lg"
    XL = "xl"
