"""Named sizes support for DaisyUI components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/builders/sizes.ipynb.

# %% auto 0
__all__ = ['DaisyUINamedSize']

# %% ../../nbs/builders/sizes.ipynb 3
from enum import Enum
from cjm_fasthtml_tailwind.core.base import NamedScale

# %% ../../nbs/builders/sizes.ipynb 5
# DaisyUI names sizes
class DaisyUINamedSize(str, Enum):
    XS = "xs"
    SM = "sm"
    MD = "md"
    LG = "lg"
    XL = "xl"
