"""Breadcrumbs helps users to navigate through the website."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/navigation/breadcrumbs.ipynb.

# %% auto 0
__all__ = ['breadcrumbs', 'test_breadcrumbs_basic_examples']

# %% ../../../nbs/components/navigation/breadcrumbs.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/navigation/breadcrumbs.ipynb 5
breadcrumbs = SingleValueFactory("breadcrumbs", "Breadcrumbs component for helping users navigate.") # Breadcrumbs component

# %% ../../../nbs/components/navigation/breadcrumbs.ipynb 7
def test_breadcrumbs_basic_examples():
    """Test breadcrumbs utility."""
    # Breadcrumb
    assert str(breadcrumbs) == "breadcrumbs"

    # Breadcrumbs with modifiers
    assert str(breadcrumbs.hover) == "hover:breadcrumbs"
    assert str(breadcrumbs.md) == "md:breadcrumbs"
    assert str(breadcrumbs.dark) == "dark:breadcrumbs"

# Run the tests
test_breadcrumbs_basic_examples()
