"""Dock (also know as Bottom navigation or Bottom bar) is a UI element that provides navigation options to the user. Dock sticks to the bottom of the screen."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/navigation/dock.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/navigation/dock.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
