"""Navbar is used to show a navigation bar on the top of the page.."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/navigation/navbar.ipynb.

# %% auto 0
__all__ = ['navbar', 'navbar_start', 'navbar_center', 'navbar_end', 'test_navbar_basic_examples']

# %% ../../../nbs/components/navigation/navbar.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/navigation/navbar.ipynb 5
navbar = SingleValueFactory("navbar", "Base navigation bar component") # Base navbar component
navbar_start = SingleValueFactory("navbar-start", "Navbar start part for the div inside navbar, to fill 50% of width") # Navbar start part
navbar_center = SingleValueFactory("navbar-center", "Navbar center part for the div inside navbar, to be at center horizontally") # Navbar center part
navbar_end = SingleValueFactory("navbar-end", "Navbar part for the div inside navbar, to fill second 50% of width") # Navbar end part

# %% ../../../nbs/components/navigation/navbar.ipynb 7
def test_navbar_basic_examples():
    """Test basic navbar utilities."""
    # Basic navbar
    assert str(navbar) == "navbar"
    assert str(navbar_start) == "navbar-start"
    assert str(navbar_center) == "navbar-center"
    assert str(navbar_end) == "navbar-end"
    
    # navbar with modifiers
    assert str(navbar.hover) == "hover:navbar"
    assert str(navbar.md) == "md:navbar"
    assert str(navbar.dark) == "dark:navbar"

# Run the tests
test_navbar_basic_examples()
