"""Pagination is a group of buttons that allow the user to navigate between a set of related content."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/navigation/pagination.ipynb.

# %% auto 0
__all__ = ['test_pagination_basic_examples', 'test_pagination_directions_examples']

# %% ../../../nbs/components/navigation/pagination.ipynb 3
from ..layout.join import join, join_item, join_directions

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/navigation/pagination.ipynb 6
def test_pagination_basic_examples():
    """Test basic pagination utilities."""
    # Basic join
    assert str(join) == "join"
    assert str(join_item) == "join-item"
    
    # Test with modifiers
    assert str(join.hover) == "hover:join"
    assert str(join.md) == "md:join"
    assert str(join.dark) == "dark:join"

    assert str(join_item.hover) == "hover:join-item"
    assert str(join_item.md) == "md:join-item"
    assert str(join_item.dark) == "dark:join-item"

# Run the tests
test_pagination_basic_examples()

# %% ../../../nbs/components/navigation/pagination.ipynb 7
def test_pagination_directions_examples():
    """Test join directions variants."""
    assert str(join_directions.vertical) == "join-vertical"
    assert str(join_directions.horizontal) == "join-horizontal"

# Run the tests
test_pagination_directions_examples()
