"""Pagination is a group of buttons that allow the user to navigate between a set of related content."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/navigation/pagination.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/navigation/pagination.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
