"""Base classes and types for all daisyUI components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/base.ipynb.

# %% auto 0
__all__ = ['HasSize', 'DaisyComponent', 'ValidatedDaisyComponent']

# %% ../../nbs/core/base.ipynb 3
from typing import Dict, Any, Optional, List, Union, Literal
from dataclasses import dataclass, field
from enum import Enum
from fasthtml.common import *
from cjm_tailwind_utils.all import TailwindBuilder
from cjm_fasthtml_daisyui.core.types import (
    # Enums
    DaisyPosition,
    DaisyBreakpoint,
    DaisySize,
    SemanticColor,
    ColorUtility,
    DaisyComponentType,
    # Protocols
    CSSContributor,
    ComponentProtocol,
    FeatureSupport,
    # Utility functions
    ensure_list,
    ensure_dict
)
from cjm_fasthtml_daisyui.core.colors import (
    ColorBuilder, ColorMixin,
    apply_semantic_colors, get_color_classes
)

# %% ../../nbs/core/base.ipynb 5
@dataclass 
class HasSize(CSSContributor):
    """Mixin for components that support size modifiers.
    
    This mixin provides size support for daisyUI components,
    including responsive size variations.
    
    Note: This mixin expects to be used with a class that has a
    component_class() method (like DaisyComponent).
    """
    
    # Size properties
    size: Optional[Union[DaisySize, str]] = None
    responsive_size: Optional[Dict[str, str]] = None  # e.g., {"md": "lg", "lg": "xl"}
    
    def get_css_classes(
        self
    ) -> List[str]:  # List of CSS class strings for size modifiers
        """Get size-related CSS classes.
        
        Returns:
            List of CSS class strings for size modifiers
        """
        classes: List[str] = []
        
        # Only add size classes if we have a component_class method
        if hasattr(self, 'component_class') and callable(self.component_class):
            try:
                base_class = self.component_class()
                
                # Add size modifier
                if self.size:
                    size_val = self.size.value if isinstance(self.size, DaisySize) else self.size
                    classes.append(f"{base_class}-{size_val}")
                
                # Add responsive size modifiers  
                if self.responsive_size:
                    for breakpoint, size in self.responsive_size.items():
                        classes.append(f"{breakpoint}:{base_class}-{size}")
            except:
                # If component_class raises an error, skip size classes
                pass
                
        return classes

# %% ../../nbs/core/base.ipynb 7
@dataclass
class DaisyComponent(ColorMixin, ComponentProtocol):
    """Base class for all daisyUI components.
    
    This class provides the foundation for building daisyUI components with:
    - Type-safe semantic color support with automatic content colors
    - Custom class and attribute support
    - Integration with cjm-tailwind-utils for additional styling
    - Responsive modifier support
    - Full implementation of ComponentProtocol interface
    """
    
    # HTML attributes
    id: Optional[str] = None
    cls: Optional[str] = None  # Additional custom classes
    attrs: Dict[str, Any] = field(default_factory=dict)
    
    # Responsive modifiers
    responsive_hide: Optional[List[str]] = None  # Breakpoints to hide at
    responsive_show: Optional[List[str]] = None  # Breakpoints to show at
    
    # Additional Tailwind customization
    tw_padding: Optional[Union[int, str]] = None
    tw_margin: Optional[Union[int, str]] = None
    tw_utilities: Optional[List[str]] = None  # Raw Tailwind utilities
    
    def component_class(
        self
    ) -> str:  # The base component class name (e.g., 'btn', 'card')
        """Return the base component class name (e.g., 'btn', 'card').
        
        Subclasses must implement this method.
        """
        raise NotImplementedError("Subclasses must implement component_class()")
    
    def modifier_classes(
        self
    ) -> List[str]:  # List of modifier CSS classes
        """Return all modifier classes for this component."""
        # Subclasses should override this to add their specific modifiers
        return []
    
    def build_classes(
        self
    ) -> str:  # Space-separated string of all CSS classes
        """Build complete class string with deduplication."""
        # Use a set to collect all unique classes
        all_classes = set()
        
        # Add component classes
        all_classes.add(self.component_class())
        all_classes.update(self.modifier_classes())
        
        # Add padding/margin
        tb = TailwindBuilder()
        if self.tw_padding is not None:
            tb.p(self.tw_padding)
        if self.tw_margin is not None:
            tb.m(self.tw_margin)
        
        # Get padding/margin classes from TailwindBuilder
        if tb.build():
            all_classes.update(ensure_list(tb.build()))
            
        # Add responsive visibility
        if self.responsive_hide:
            for bp in self.responsive_hide:
                all_classes.add(f"{bp}:hidden")
        if self.responsive_show:
            for bp in self.responsive_show:
                all_classes.add(f"{bp}:block")
                
        # Add raw utilities
        if self.tw_utilities:
            all_classes.update(self.tw_utilities)
            
        # Collect CSS classes from all mixins that implement get_css_classes
        # Track which actual methods we've called to avoid duplicates
        called_methods = set()
        
        # Check each class in the MRO for get_css_classes method
        for cls in type(self).__mro__:
            if hasattr(cls, 'get_css_classes'):
                method = getattr(cls, 'get_css_classes')
                # Check if this is a unique method (not inherited)
                method_id = id(method.__func__ if hasattr(method, '__func__') else method)
                if callable(method) and method_id not in called_methods:
                    try:
                        result = method(self)
                        if result:
                            all_classes.update(result)
                        called_methods.add(method_id)
                    except:
                        pass
        
        # Add custom classes last
        if self.cls:
            all_classes.update(ensure_list(self.cls))
            
        # Convert set back to list and join
        # Sort to ensure consistent order
        return " ".join(sorted(all_classes))
    
    def render_attrs(
        self
    ) -> Dict[str, Any]:  # Dictionary of HTML attributes
        """Build all HTML attributes for rendering."""
        attrs: Dict[str, Any] = {**self.attrs}
        attrs["class"] = self.build_classes()
        
        if self.id:
            attrs["id"] = self.id
            
        return attrs
        
    def with_utilities(
        self,
        *utilities: str # Tailwind utility classes to add
    ) -> 'DaisyComponent':  # Self for method chaining
        """Add Tailwind utilities and return self for chaining."""
        if self.tw_utilities is None:
            self.tw_utilities = []
        self.tw_utilities.extend(utilities)
        return self
    
    def with_semantic_colors(
        self,
        bg: Optional[Union[SemanticColor, str]] = None, # Background color
        text: Optional[Union[SemanticColor, str]] = None, # Text color (auto-selected if None and auto_content=True)
        border: Optional[Union[SemanticColor, str]] = None, # Border color
        auto_content: bool = True  # Automatically select appropriate text color for background
    ) -> 'DaisyComponent':  # Self for method chaining
        """Apply semantic colors with automatic content color selection."""
        classes = ensure_list(apply_semantic_colors(bg, text, border, auto_content))
        return self.with_utilities(*classes)

# %% ../../nbs/core/base.ipynb 9
@dataclass
class ValidatedDaisyComponent(DaisyComponent):
    """Extended base class with component type validation.
    
    This optional base class adds validation to ensure component classes
    match known daisyUI component types.
    """
    
    # Component type for validation
    component_type: Optional[DaisyComponentType] = None
    
    def component_class(
        self
    ) -> str:  # The base component class name with validation
        """Return the base component class name with validation.
        
        If component_type is set, returns its value.
        Otherwise falls back to the standard implementation.
        """
        if self.component_type:
            return self.component_type.value
        return super().component_class()
    
    def validate_component_type(
        self
    ) -> None: # Validates component type if specified
        """Validate component type if specified.
        
        This should be called by subclasses after they've set up
        their component_type and implemented component_class.
        """
        if self.component_type:
            # For validation, temporarily clear component_type to get the actual class
            temp_type = self.component_type
            self.component_type = None
            try:
                actual = self.component_class()
            except NotImplementedError:
                # If component_class is not implemented yet, skip validation
                actual = None
            finally:
                self.component_type = temp_type
                
            if actual and actual != self.component_type.value:
                raise ValueError(
                    f"Component class mismatch: expected '{self.component_type.value}' "
                    f"but got '{actual}' for {self.component_type.name}"
                )
