"""Standardized testing framework for daisyUI components in Jupyter notebooks"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/testing.ipynb.

# %% auto 0
__all__ = ['DisplayMode', 'ComponentExample', 'ComponentTester', 'quick_test', 'test_variants', 'theme_test', 'ComponentBuilder',
           'TestData']

# %% ../../nbs/core/testing.ipynb 2
from typing import List, Optional, Union, Callable, Any, Dict, Tuple
from dataclasses import dataclass, field
from enum import Enum
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
import asyncio
from contextlib import contextmanager
import time

# Import cjm-tailwind-utils for dynamic CSS generation
from cjm_tailwind_utils.all import TailwindBuilder

# %% ../../nbs/core/testing.ipynb 3
# Import our own modules
from cjm_fasthtml_daisyui.core.types import (
    # Enums and main types
    SemanticColor, ColorUtility, DaisyUITheme, DaisyComponentType,
    DaisyPosition, DaisyBreakpoint, DaisySize, Direction,
    HTMXTrigger, HTMXSwap, StyleType,
    # Type aliases
    CSSClasses, CSSClass, HTMLAttrs, Children, ComponentProps,
    ResponsiveDict, ColorValue, SizeValue, EventHandler, 
    ComponentFactory, HTMXValue,
    # Literal types
    DirectionType, PlacementType, HTTPMethod, ColorSchemeType,
    # Protocols
    CSSContributor, FeatureSupport, ComponentProtocol,
    # Utility functions
    ensure_list, ensure_dict
)
from .resources import DaisyUIResources, ResourcePresets
from .config import DaisyUIConfig, ThemeConfig
from .colors import ColorBuilder, apply_semantic_colors

# %% ../../nbs/core/testing.ipynb 5
class DisplayMode(str, Enum):
    """Component display modes for testing"""
    INLINE = "inline"      # Components side by side
    STACKED = "stacked"    # Components stacked vertically
    GRID = "grid"          # Components in a grid
    SECTIONS = "sections"  # Components in labeled sections

# %% ../../nbs/core/testing.ipynb 6
@dataclass
class ComponentExample:
    """Container for a component example with metadata"""
    component: FT
    title: str
    description: Optional[str] = None
    code: Optional[str] = None
    props: Optional[ComponentProps] = None
    component_type: Optional[DaisyComponentType] = None

# %% ../../nbs/core/testing.ipynb 7
class ComponentTester:
    """
    Standardized testing framework for daisyUI components in notebooks
    
    Provides an interactive environment for testing and showcasing components
    with theme switching, responsive preview, and documentation.
    """
    
    def __init__(
        self,
        title: str = "Component Showcase",  # Title for the showcase page
        pico: bool = False,  # Whether to include Pico CSS (should be False for daisyUI)
        config: Optional[DaisyUIConfig] = None,  # daisyUI configuration (only used with local resources)
        use_cdn: bool = True,  # Whether to use CDN resources (vs local)
        port: Optional[int] = 8000,  # Port for the test server
        available_themes: Optional[List[Union[DaisyUITheme, str]]] = None # List of themes to show in selector (defaults to all when using CDN)
    ):
        """Initialize the component tester"""
        self.title = title
        self.use_cdn = use_cdn
        self.port = port
        
        # Store headers for later use in rendering
        if use_cdn:
            # CDN includes all themes, so we ignore config for theme selection
            self.available_themes = available_themes or list(DaisyUITheme)
            self.hdrs = ResourcePresets.development()
        else:
            # Local resources can be configured
            self.config = config or DaisyUIConfig()
            self.available_themes = self._extract_themes_from_config(self.config)
            self.hdrs = ResourcePresets.production()
            
            # Add configuration CSS for local resources
            if config:
                self.hdrs.insert(0, DaisyUIResources.inline_css(config.to_css()))
        
        # Create FastHTML app
        self.app, self.rt = fast_app(pico=pico, hdrs=self.hdrs)
        self.server = None
        self.examples: List[ComponentExample] = []
        self._setup_routes()
    
    def _extract_themes_from_config(
        self,
        config: DaisyUIConfig  # The configuration to extract themes from
    ) -> List[str]:  # List of theme names as strings
        """Extract theme names from configuration"""
        themes = []
        for theme in config.themes:
            if isinstance(theme, ThemeConfig):
                theme_name = theme.name.value if isinstance(theme.name, DaisyUITheme) else theme.name
                themes.append(theme_name)
            elif isinstance(theme, DaisyUITheme):
                themes.append(theme.value)
            else:
                themes.append(str(theme))
        return themes
    
    def _setup_routes(
        self
    ) -> None:  # No return value
        """Set up default routes"""
        @self.rt('/')
        def index(
        ) -> FT:  # The rendered showcase page
            """Render the main showcase page"""
            return self._render_showcase()
        
        @self.rt('/theme/{theme}')
        def set_theme(
            theme: str  # The theme name to apply
        ) -> FT:  # Script tag that applies the theme
            """Route to change theme dynamically"""
            return Script(f'document.documentElement.setAttribute("data-theme", "{theme}")')
    
    def add(
        self,
        component: Union[FT, ComponentFactory],
        title: str,  # Title for this component example
        description: Optional[str] = None,  # Optional description of the component
        code: Optional[str] = None,  # Optional code snippet to display
        component_type: Optional[DaisyComponentType] = None,  # The daisyUI component type for categorization
        **props: Any # Properties passed to the component if it's a function
    ) -> "ComponentTester":  # Returns self for chaining
        """Add a component example to the showcase"""
        if callable(component):
            comp = component(**props)
        else:
            comp = component
            
        self.examples.append(ComponentExample(
            component=comp,
            title=title,
            description=description,
            code=code,
            props=props,
            component_type=component_type
        ))
        return self
    
    def showcase(
        self,
        *components: FT, # Components to showcase
        mode: DisplayMode = DisplayMode.SECTIONS, # How to display the components
        titles: Optional[List[str]] = None #  Optional titles for each component
    ) -> "ComponentTester":  # Returns self for chaining
        """Quick method to add multiple components"""
        for i, comp in enumerate(components):
            title = titles[i] if titles and i < len(titles) else f"Example {i+1}"
            self.add(comp, title)
        
        self.display_mode = mode
        return self
    
    def _render_showcase(
        self
    ) -> FT:  # The complete showcase page
        """Render the complete showcase page"""
        # Note: FastHTML app already includes headers, so we just return the body content
        return Div(
            # Navigation bar with theme switcher
            self._render_navbar(),
            
            # Main content area
            Main(
                Div(
                    H1(self.title, cls=TailwindBuilder().text(size="4xl", weight="bold").m(8, "b").build()),
                    
                    # Component examples
                    self._render_examples(),
                    
                    cls=TailwindBuilder().m("auto", "x").p(4, "x").p(8, "y").build()
                ),
                cls=(TailwindBuilder()
                     .add_class("container")
                     .min_h("screen")
                     .add_class(ColorUtility.BACKGROUND.with_color(SemanticColor.BASE_100))
                     .build())
            ),
            
            # Footer with color palette
            self._render_footer()
        )
    
    def _render_navbar(
        self
    ) -> FT:  # The navigation bar component
        """Render navigation bar with theme switcher"""
        # Get theme names as strings
        theme_names = []
        for theme in self.available_themes:
            if isinstance(theme, DaisyUITheme):
                theme_names.append(theme.value)
            else:
                theme_names.append(str(theme))
        
        return Nav(
            Div(
                # Logo/Title
                A(self.title, cls=TailwindBuilder().add_class("btn btn-ghost").text(size="xl").build()),
                
                # Theme switcher
                Div(
                    Label("Theme:", cls="label"),
                    Select(
                        *[Option(t.title(), value=t, selected=(i==0)) for i, t in enumerate(theme_names)],
                        cls="select select-bordered select-sm",
                        onchange="document.documentElement.setAttribute('data-theme', this.value)"
                    ),
                    cls=TailwindBuilder().flex().items("center").gap(2).build()
                ),
                
                cls=(TailwindBuilder()
                     .add_class("navbar")
                     .add_class(ColorUtility.BACKGROUND.with_color(SemanticColor.BASE_200))
                     .p(4, "x")
                     .build())
            ),
            cls=TailwindBuilder().position("sticky").inset(0, "top").z(50).build()
        )
    
    def _render_examples(
        self
    ) -> FT:  # Container with all component examples
        """Render all component examples"""
        if not self.examples:
            return Div(
                P("No components added yet. Use .add() or .showcase() to add components."),
                cls=TailwindBuilder().add_class("text-base-content/70").build()
            )
        
        sections = []
        for example in self.examples:
            section = self._render_example(example)
            sections.append(section)
        
        # Apply display mode
        container_cls = {
            DisplayMode.INLINE: TailwindBuilder().flex(wrap="wrap").gap(4).build(),
            DisplayMode.STACKED: TailwindBuilder().space(6, "y").build(),
            DisplayMode.GRID: (TailwindBuilder()
                              .grid(cols=1)
                              .add_class("md:grid-cols-2 lg:grid-cols-3")
                              .gap(6)
                              .build()),
            DisplayMode.SECTIONS: TailwindBuilder().space(8, "y").build()
        }.get(getattr(self, 'display_mode', DisplayMode.SECTIONS), TailwindBuilder().space(8, "y").build())
        
        return Div(*sections, cls=container_cls)
    
    def _render_example(
        self,
        example: ComponentExample  # The example to render
    ) -> FT:  # The rendered example section
        """Render a single component example"""
        elements = []
        
        # Title
        elements.append(H3(example.title, cls=TailwindBuilder().text(size="xl", weight="semibold").m(2, "b").build()))
        
        # Component type badge if provided
        if example.component_type:
            elements.append(
                Span(
                    f"{example.component_type.get_category()} / {example.component_type.name}",
                    cls=TailwindBuilder().add_class("badge badge-neutral badge-sm").m(2, "b").build()
                )
            )
        
        # Description
        if example.description:
            elements.append(P(example.description, cls=(TailwindBuilder()
                                                        .add_class("text-base-content/70")
                                                        .m(4, "b")
                                                        .build())))
        
        # Component preview
        elements.append(
            Div(
                example.component,
                cls=(TailwindBuilder()
                     .p(6)
                     .add_class(ColorUtility.BACKGROUND.with_color(SemanticColor.BASE_200))
                     .rounded("lg")
                     .build())
            )
        )
        
        # Code snippet
        if example.code:
            elements.append(
                Details(
                    Summary("View Code", cls=TailwindBuilder().cursor("pointer").text(weight="medium").m(4, "t").build()),
                    Pre(
                        Code(example.code, cls="language-python"),
                        cls=TailwindBuilder().add_class("mockup-code").m(2, "t").build()
                    ),
                    cls=TailwindBuilder().m(4, "t").build()
                )
            )
        
        return Section(*elements, cls="")
    
    def _render_footer(
        self
    ) -> FT:  # The footer component
        """Render footer with color palette"""
        return Footer(
            Div(
                H4("Color Palette", cls=TailwindBuilder().text(size="lg", weight="semibold").m(4, "b").build()),
                self._render_color_palette(),
                cls=(TailwindBuilder()
                     .add_class("footer footer-center")
                     .p(8)
                     .add_class(apply_semantic_colors(
                         bg=SemanticColor.BASE_200,
                         text=SemanticColor.BASE_CONTENT
                     ))
                     .build())
            )
        )
    
    def _render_color_palette(
        self
    ) -> FT:  # The color palette display
        """Render the current theme's color palette"""
        colors = [
            ("primary", "Primary"),
            ("secondary", "Secondary"),
            ("accent", "Accent"),
            ("neutral", "Neutral"),
            ("base-100", "Base"),
            ("info", "Info"),
            ("success", "Success"),
            ("warning", "Warning"),
            ("error", "Error")
        ]
        
        swatches = []
        for color_class, label in colors:
            swatches.append(
                Div(
                    Div(cls=TailwindBuilder().w(12).h(12).rounded("lg").add_class(f"bg-{color_class}").build()),
                    Span(label, cls=TailwindBuilder().text(size="xs").m(1, "t").build()),
                    cls=TailwindBuilder().flex(direction="col").items("center").build()
                )
            )
        
        return Div(*swatches, cls=TailwindBuilder().flex(wrap="wrap").gap(4).justify("center").build())
    
    def start(
        self,
        open_browser: bool = False  # Whether to automatically open the browser
    ) -> "ComponentTester":  # Returns self for chaining
        """Start the test server"""
        if not self.server:
            self.server = JupyUvi(self.app, port=self.port)
            if open_browser:
                HTMX()  # This will display the link in Jupyter
        return self
    
    def stop(
        self
    ) -> None:  # No return value
        """Stop the test server"""
        if self.server:
            self.server.stop()
            self.server = None
    
    def __enter__(self):
        """Context manager support"""
        return self.start()
    
    def __exit__(
        self,
        exc_type: Any,  # Exception type if an exception occurred
        exc_val: Any,  # Exception value if an exception occurred
        exc_tb: Any  # Exception traceback if an exception occurred
    ) -> None:  # No return value
        """Context manager cleanup"""
        self.stop()

# %% ../../nbs/core/testing.ipynb 9
def quick_test(
    *components: FT,
    title: str = "Quick Test"  # Title for the test page
) -> ComponentTester:  # Started ComponentTester instance
    "Quick function to test components"
    tester = ComponentTester(title=title)
    tester.showcase(*components)
    return tester.start()

# %% ../../nbs/core/testing.ipynb 10
def test_variants(
    component_fn: ComponentFactory,  # Function that creates the component
    variants: Dict[str, List[Any]],
    base_props: Optional[ComponentProps] = None,  # Base properties to apply to all variants
    title: str = "Variant Testing"  # Title for the test page
) -> ComponentTester:  # Started ComponentTester instance
    "Test multiple variants of a component"
    tester = ComponentTester(title=title)
    base_props = base_props or {}
    
    # Generate all combinations
    import itertools
    
    if variants:
        keys = list(variants.keys())
        values = list(variants.values())
        
        for combo in itertools.product(*values):
            props = {**base_props}
            variant_desc = []
            
            for i, key in enumerate(keys):
                props[key] = combo[i]
                variant_desc.append(f"{key}={combo[i]}")
            
            component = component_fn(**props)
            title = " + ".join(variant_desc)
            
            tester.add(component, title, props=props)
    else:
        # No variants, just test base
        component = component_fn(**base_props)
        tester.add(component, "Base", props=base_props)
    
    return tester.start()

# %% ../../nbs/core/testing.ipynb 11
@contextmanager
def theme_test(
    themes: Optional[List[Union[DaisyUITheme, str]]] = None  # List of themes to test with (uses all themes if None)
):
    "Context manager for testing with specific themes"
    # When using CDN, we just control which themes are shown in the selector
    tester = ComponentTester(
        title="Theme Testing",
        available_themes=themes or list(DaisyUITheme)
    )
    
    try:
        yield tester
        tester.start()
    finally:
        # Keep server running in notebook context
        pass

# %% ../../nbs/core/testing.ipynb 13
class ComponentBuilder:
    """Interactive component builder for notebooks"""
    
    def __init__(
        self,
        title: str = "Component Builder"  # Title for the builder page
    ):
        """Initialize the component builder"""
        self.tester = ComponentTester(title=title)
        self.current_component = None
        self.component_history: List[FT] = []
    
    def create(
        self,
        tag: str = "div",  # HTML tag name for the component
        *children: Any,
        **attrs: Any
    ) -> "ComponentBuilder":  # Returns self for chaining
        """Create a new component"""
        self.current_component = NotStr(tag, *children, **attrs)
        self.component_history.append(self.current_component)
        return self
    
    def add_class(
        self,
        *classes: CSSClass
    ) -> "ComponentBuilder":  # Returns self for chaining
        """Add classes to the current component"""
        if self.current_component and hasattr(self.current_component, 'attrs'):
            current_cls = self.current_component.attrs.get('cls', '')
            new_cls = f"{current_cls} {' '.join(classes)}".strip()
            self.current_component.attrs['cls'] = new_cls
        return self
    
    def add_child(
        self,
        child: FT  # Child component to add
    ) -> "ComponentBuilder":  # Returns self for chaining
        """Add a child to the current component"""
        if self.current_component:
            self.current_component.children = list(self.current_component.children) + [child]
        return self
    
    def preview(
        self,
        title: Optional[str] = None  # Optional title for the preview
    ) -> "ComponentBuilder":  # Returns self for chaining
        """Preview the current component"""
        if self.current_component:
            title = title or f"Component {len(self.component_history)}"
            self.tester.add(self.current_component, title)
        return self
    
    def show(
        self
    ) -> ComponentTester:  # The started tester instance
        """Show all previewed components"""
        return self.tester.start()
    
    def reset(
        self
    ) -> "ComponentBuilder":  # Returns self for chaining
        """Reset the builder"""
        self.current_component = None
        self.component_history = []
        self.tester = ComponentTester(self.tester.title)
        return self

# %% ../../nbs/core/testing.ipynb 15
class TestData:
    """Generate test data for components"""
    
    @staticmethod
    def lorem(
        words: int = 10  # Number of words to generate
    ) -> str:  # Lorem ipsum text
        """Generate lorem ipsum text"""
        lorem_words = [
            "lorem", "ipsum", "dolor", "sit", "amet", "consectetur",
            "adipiscing", "elit", "sed", "do", "eiusmod", "tempor",
            "incididunt", "ut", "labore", "et", "dolore", "magna",
            "aliqua", "enim", "ad", "minim", "veniam", "quis"
        ]
        result = []
        for i in range(words):
            result.append(lorem_words[i % len(lorem_words)])
        return " ".join(result).capitalize() + "."
    
    @staticmethod
    def image(
        width: int = 300,  # Image width in pixels
        height: int = 200,  # Image height in pixels
        category: str = ""  # Optional category for the image
    ) -> str:  # URL to placeholder image
        """Generate placeholder image URL"""
        if category:
            return f"https://picsum.photos/{width}/{height}?{category}"
        return f"https://picsum.photos/{width}/{height}"
    
    @staticmethod
    def avatar(
        size: int = 100,  # Avatar size in pixels
        seed: Optional[str] = None  # Optional seed for consistent avatars
    ) -> str:  # URL to avatar image
        """Generate avatar URL"""
        if seed:
            return f"https://api.dicebear.com/7.x/avataaars/svg?seed={seed}&size={size}"
        return f"https://api.dicebear.com/7.x/avataaars/svg?size={size}"
    
    @staticmethod
    def items(
        count: int = 5,  # Number of items to generate
        prefix: str = "Item"  # Prefix for each item
    ) -> List[str]:  # List of generated items
        """Generate list of items"""
        return [f"{prefix} {i+1}" for i in range(count)]
    
    @staticmethod
    def table_data(
        rows: int = 5,  # Number of data rows (excluding header)
        cols: int = 3  # Number of columns
    ) -> List[List[str]]:  # 2D list with headers and data
        """Generate table data"""
        headers = [f"Column {i+1}" for i in range(cols)]
        data = []
        for r in range(rows):
            row = [f"Cell {r+1}-{c+1}" for c in range(cols)]
            data.append(row)
        return [headers] + data
