"""Calendar includes styles for different calendar libraries."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/data_input/calendar.ipynb.

# %% auto 0
__all__ = ['cally', 'pika_single', 'react_day_picker', 'test_calendar_basic_examples',
           'test_calendar_cally_basic_fasthtml_example']

# %% ../../../nbs/components/data_input/calendar.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/data_input/calendar.ipynb 5
cally = SingleValueFactory("cally", "Base calendar component for Cally web component") # Base Cally calendar component
pika_single = SingleValueFactory("pika-single", "Base calendar component for the input field that opens Pikaday calendar") # Base Pikaday calender component
react_day_picker = SingleValueFactory("react-day-picker", "Base calendar component for the DayPicker component") # Base DayPicker calendar component

# %% ../../../nbs/components/data_input/calendar.ipynb 7
def test_calendar_basic_examples():
    """Test basic calendar utilities."""
    # Basic calendar
    assert str(cally) == "cally"
    assert str(pika_single) == "pika-single"
    assert str(react_day_picker) == "react-day-picker"
    
    # Test with modifiers
    assert str(cally.hover) == "hover:cally"
    assert str(pika_single.md) == "md:pika-single"
    assert str(react_day_picker.dark) == "dark:react-day-picker"

# Run the tests
test_calendar_basic_examples()

# %% ../../../nbs/components/data_input/calendar.ipynb 8
def test_calendar_cally_basic_fasthtml_example():
    """Test Cally calendar example from daisyUI v5 documentation."""
    from fasthtml.common import Div, Script
    from fasthtml.core import FT
    from fasthtml.svg import Svg, Path
    from cjm_fasthtml_tailwind.utilities.sizing import size_util
    from cjm_fasthtml_tailwind.utilities.svg import fill
    from cjm_fasthtml_tailwind.utilities.borders import border
    from cjm_fasthtml_tailwind.utilities.effects import shadow
    from cjm_fasthtml_tailwind.core.base import SingleValueFactory
    from cjm_fasthtml_daisyui.core.utility_classes import bg_dui, border_dui
    
    # Create rounded-box factory
    rounded_box = SingleValueFactory('rounded-box', 'Rounded box utility')
    
    # Create custom calendar elements using FT
    def CalendarDate(*children, **kwargs):
        return FT('calendar-date', children, kwargs)
    
    def CalendarMonth(*children, **kwargs):
        return FT('calendar-month', children, kwargs)
    
    # Create navigation icons
    prev_icon = Svg(
        Path(
            fill="currentColor",
            d="M15.75 19.5 8.25 12l7.5-7.5"
        ),
        aria_label="Previous",
        cls=combine_classes(fill.current, size_util._4),
        slot="previous",
        xmlns="http://www.w3.org/2000/svg",
        viewBox="0 0 24 24"
    )
    
    next_icon = Svg(
        Path(
            fill="currentColor",
            d="m8.25 4.5 7.5 7.5-7.5 7.5"
        ),
        aria_label="Next",
        cls=combine_classes(fill.current, size_util._4),
        slot="next",
        xmlns="http://www.w3.org/2000/svg",
        viewBox="0 0 24 24"
    )
    
    # Create Cally calendar
    calendar = CalendarDate(
        prev_icon,
        next_icon,
        CalendarMonth(),
        cls=combine_classes(cally, bg_dui.base_100, border, border_dui.base_300, shadow.lg, rounded_box)
    )
    
    # Add script to import Cally web component
    script = Script(
        type="module",
        src="https://unpkg.com/cally"
    )
    
    # # Verify structure
    # assert calendar.tag == "calendar-date"
    # assert "cally" in calendar.attrs['class']
    # assert "bg-base-100" in calendar.attrs['class']
    # assert "border" in calendar.attrs['class']
    # assert "border-base-300" in calendar.attrs['class']
    # assert "shadow-lg" in calendar.attrs['class']
    # assert "rounded-box" in calendar.attrs['class']
    
    # # Check children
    # assert len(calendar.children) == 3  # prev icon, next icon, calendar-month
    
    # # Check prev icon
    # assert calendar.children[0].tag == "svg"
    # assert calendar.children[0].attrs['aria-label'] == "Previous"
    # assert calendar.children[0].attrs['slot'] == "previous"
    # assert "fill-current" in calendar.children[0].attrs['class']
    # assert "size-4" in calendar.children[0].attrs['class']
    
    # # Check next icon
    # assert calendar.children[1].tag == "svg"
    # assert calendar.children[1].attrs['aria-label'] == "Next"
    # assert calendar.children[1].attrs['slot'] == "next"
    
    # # Check calendar-month
    # assert calendar.children[2].tag == "calendar-month"
    
    # Return the calendar with script
    return Div(
        script,
        calendar
    )

# Run the tests
test_calendar_cally_basic_fasthtml_example()
