"""File Input is a an input field for uploading files."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/data_input/file_input.ipynb.

# %% auto 0
__all__ = ['file_input', 'file_input_styles', 'file_input_colors', 'file_input_sizes', 'test_file_input_basic_examples',
           'test_file_input_styles_examples', 'test_file_input_colors_examples', 'test_file_input_sizes_examples']

# %% ../../../nbs/components/data_input/file_input.ipynb 3
from typing import Optional, Dict, Any, Union
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from cjm_fasthtml_tailwind.builders.scales import SimpleFactory, enums_to_simple_factory

from ...builders.colors import SemanticColorBrand, SemanticColorStatus
from ...builders.sizes import DaisyUINamedSize
from ...builders.styles import GhostStyle

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/data_input/file_input.ipynb 5
file_input = SingleValueFactory("file-input", "Base file input component for <input type=\"file\"> element") # Base file input component

# %% ../../../nbs/components/data_input/file_input.ipynb 7
file_input_styles = enums_to_simple_factory(file_input, [GhostStyle]) # File input style variants

# %% ../../../nbs/components/data_input/file_input.ipynb 9
file_input_colors = enums_to_simple_factory(file_input, [SemanticColorBrand, SemanticColorStatus], "File input color variants using daisyUI semantic colors") # File input color variants

# %% ../../../nbs/components/data_input/file_input.ipynb 11
file_input_sizes = enums_to_simple_factory(file_input, [DaisyUINamedSize], "File input size variants from extra small to extra large") # File input size variants

# %% ../../../nbs/components/data_input/file_input.ipynb 13
def test_file_input_basic_examples():
    """Test basic file_input utilities."""
    # Basic file_input
    assert str(file_input) == "file-input"
    
    # Test with modifiers
    assert str(file_input.hover) == "hover:file-input"
    assert str(file_input.md) == "md:file-input"
    assert str(file_input.dark) == "dark:file-input"

# Run the tests
test_file_input_basic_examples()

# %% ../../../nbs/components/data_input/file_input.ipynb 14
def test_file_input_styles_examples():
    """Test file_input style variants."""
    assert str(file_input_styles.ghost) == "file-input-ghost"

# Run the tests
test_file_input_styles_examples()

# %% ../../../nbs/components/data_input/file_input.ipynb 15
def test_file_input_colors_examples():
    """Test file_input color variants."""
    # All color variants
    assert str(file_input_colors.neutral) == "file-input-neutral"
    assert str(file_input_colors.primary) == "file-input-primary"
    assert str(file_input_colors.secondary) == "file-input-secondary"
    assert str(file_input_colors.accent) == "file-input-accent"
    assert str(file_input_colors.info) == "file-input-info"
    assert str(file_input_colors.success) == "file-input-success"
    assert str(file_input_colors.warning) == "file-input-warning"
    assert str(file_input_colors.error) == "file-input-error"
    
    # With modifiers
    assert str(file_input_colors.primary.hover) == "hover:file-input-primary"
    assert str(file_input_colors.success.focus) == "focus:file-input-success"

# Run the tests
test_file_input_colors_examples()

# %% ../../../nbs/components/data_input/file_input.ipynb 16
def test_file_input_sizes_examples():
    """Test file_input size variants."""
    assert str(file_input_sizes.xs) == "file-input-xs"
    assert str(file_input_sizes.sm) == "file-input-sm"
    assert str(file_input_sizes.md) == "file-input-md"
    assert str(file_input_sizes.lg) == "file-input-lg"
    assert str(file_input_sizes.xl) == "file-input-xl"
    
    # With responsive modifiers
    assert str(file_input_sizes.xs.sm) == "sm:file-input-xs"
    assert str(file_input_sizes.lg.md) == "md:file-input-lg"

# Run the tests
test_file_input_sizes_examples()
