"""Textarea allows users to enter text in multiple lines."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/data_input/textarea.ipynb.

# %% auto #0
__all__ = ['textarea', 'textarea_styles', 'textarea_colors', 'textarea_sizes', 'test_textarea_basic_examples',
           'test_textarea_styles_examples', 'test_textarea_colors_examples', 'test_textarea_sizes_examples',
           'test_textarea_basic_fasthtml_examples', 'test_textarea_ghost_fasthtml_examples',
           'test_textarea_with_form_control_fasthtml_examples', 'test_textarea_colors_fasthtml_examples',
           'test_textarea_sizes_fasthtml_examples', 'test_textarea_disabled_fasthtml_examples']

# %% ../../../nbs/components/data_input/textarea.ipynb #045c6538-403e-4222-b3bb-db20f188524d
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from cjm_fasthtml_tailwind.builders.scales import SimpleFactory, enums_to_simple_factory

from ...builders.colors import SemanticColorBrand, SemanticColorStatus
from ...builders.sizes import DaisyUINamedSize
from ...builders.styles import GhostStyle

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/data_input/textarea.ipynb #c802d106-49fb-4d34-ba04-5f54c88e165b
textarea = SingleValueFactory("textarea", "Base textarea component for <textarea> element") # Base textarea component

# %% ../../../nbs/components/data_input/textarea.ipynb #636c6bcd-2176-4191-aa39-c937893243e2
textarea_styles = enums_to_simple_factory(textarea, [GhostStyle]) # textarea style variants

# %% ../../../nbs/components/data_input/textarea.ipynb #ad2d932c-79ea-4792-bdaf-5bda859340ca
textarea_colors = enums_to_simple_factory(textarea, [SemanticColorBrand, SemanticColorStatus], "textarea color variants using daisyUI semantic colors") # textarea color variants

# %% ../../../nbs/components/data_input/textarea.ipynb #4666a5a3-26bb-4d91-b5be-f941df8f9d2f
textarea_sizes = enums_to_simple_factory(textarea, [DaisyUINamedSize], "textarea size variants from extra small to extra large") # textarea size variants

# %% ../../../nbs/components/data_input/textarea.ipynb #214654cc-9758-48f9-92e2-0892029c4512
def test_textarea_basic_examples():
    """Test basic textarea utilities."""
    # Basic textarea
    assert str(textarea) == "textarea"
    
    # Test with modifiers
    assert str(textarea.hover) == "hover:textarea"
    assert str(textarea.md) == "md:textarea"
    assert str(textarea.dark) == "dark:textarea"

# Run the tests
test_textarea_basic_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #a9d78aa3-0be8-49e6-8bfb-cb9a232ee1ee
def test_textarea_styles_examples():
    """Test textarea style variants."""
    assert str(textarea_styles.ghost) == "textarea-ghost"

# Run the tests
test_textarea_styles_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #01785a18-9bb0-4dbc-9eae-04addf6dede9
def test_textarea_colors_examples():
    """Test textarea color variants."""
    # All color variants
    assert str(textarea_colors.neutral) == "textarea-neutral"
    assert str(textarea_colors.primary) == "textarea-primary"
    assert str(textarea_colors.secondary) == "textarea-secondary"
    assert str(textarea_colors.accent) == "textarea-accent"
    assert str(textarea_colors.info) == "textarea-info"
    assert str(textarea_colors.success) == "textarea-success"
    assert str(textarea_colors.warning) == "textarea-warning"
    assert str(textarea_colors.error) == "textarea-error"
    
    # With modifiers
    assert str(textarea_colors.primary.hover) == "hover:textarea-primary"
    assert str(textarea_colors.success.focus) == "focus:textarea-success"

# Run the tests
test_textarea_colors_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #43a3d5aa-4f07-48f4-b7c3-5c63612f0fb2
def test_textarea_sizes_examples():
    """Test textarea size variants."""
    assert str(textarea_sizes.xs) == "textarea-xs"
    assert str(textarea_sizes.sm) == "textarea-sm"
    assert str(textarea_sizes.md) == "textarea-md"
    assert str(textarea_sizes.lg) == "textarea-lg"
    assert str(textarea_sizes.xl) == "textarea-xl"
    
    # With responsive modifiers
    assert str(textarea_sizes.xs.sm) == "sm:textarea-xs"
    assert str(textarea_sizes.lg.md) == "md:textarea-lg"

# Run the tests
test_textarea_sizes_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #2e3d4135-ebce-42ec-8549-81d31a913752
def test_textarea_basic_fasthtml_examples():
    """Test basic textarea example from daisyUI v5 documentation."""
    from fasthtml.common import Textarea
    
    # Basic textarea
    basic_textarea = Textarea(placeholder="Bio", cls=str(textarea))
    
    # Verify structure
    assert basic_textarea.tag == "textarea"
    assert basic_textarea.attrs['class'] == "textarea"
    assert basic_textarea.attrs['placeholder'] == "Bio"
    
    return basic_textarea

# Run the tests
test_textarea_basic_fasthtml_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #3897cee0-9df6-41ff-afc3-d95244381f86
def test_textarea_ghost_fasthtml_examples():
    """Test ghost textarea (no background) from daisyUI v5 documentation."""
    from fasthtml.common import Textarea
    
    # Ghost textarea (no background)
    ghost_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_styles.ghost)
    )
    
    # Verify structure
    assert ghost_textarea.tag == "textarea"
    assert "textarea" in ghost_textarea.attrs['class']
    assert "textarea-ghost" in ghost_textarea.attrs['class']
    assert ghost_textarea.attrs['placeholder'] == "Bio"
    
    return ghost_textarea

# Run the tests
test_textarea_ghost_fasthtml_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #c5682a5f-0a2e-495d-8c25-d17439214339
def test_textarea_with_form_control_fasthtml_examples():
    """Test textarea with form control and labels from daisyUI v5 documentation."""
    from fasthtml.common import Fieldset, Legend, Textarea, Div
    from cjm_fasthtml_tailwind.utilities.sizing import h
    from cjm_fasthtml_daisyui.components.data_input.fieldset import fieldset, fieldset_legend
    from cjm_fasthtml_daisyui.components.data_input.label import label
    
    # Textarea with form control and labels
    form_control_textarea = Fieldset(
        Legend("Your bio", cls=str(fieldset_legend)),
        Textarea(
            placeholder="Bio",
            cls=combine_classes(textarea, h._24)
        ),
        Div("Optional", cls=str(label)),
        cls=str(fieldset)
    )
    
    # Verify structure
    assert form_control_textarea.tag == "fieldset"
    assert form_control_textarea.attrs['class'] == "fieldset"
    
    # Verify legend
    legend_element = form_control_textarea.children[0]
    assert legend_element.tag == "legend"
    assert legend_element.attrs['class'] == "fieldset-legend"
    assert legend_element.children[0] == "Your bio"
    
    # Verify textarea
    textarea_element = form_control_textarea.children[1]
    assert textarea_element.tag == "textarea"
    assert "textarea" in textarea_element.attrs['class']
    assert "h-24" in textarea_element.attrs['class']
    assert textarea_element.attrs['placeholder'] == "Bio"
    
    # Verify label
    label_element = form_control_textarea.children[2]
    assert label_element.tag == "div"
    assert label_element.attrs['class'] == "label"
    assert label_element.children[0] == "Optional"
    
    return form_control_textarea

# Run the tests
test_textarea_with_form_control_fasthtml_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #8bb66ace-b651-43b7-bf43-5f97c1849ebd
def test_textarea_colors_fasthtml_examples():
    """Test textarea color variations from daisyUI v5 documentation."""
    from fasthtml.common import Textarea, Div
    
    # Textarea colors
    primary_textarea = Textarea(
        placeholder="Primary",
        cls=combine_classes(textarea, textarea_colors.primary)
    )
    assert "textarea" in primary_textarea.attrs['class']
    assert "textarea-primary" in primary_textarea.attrs['class']
    assert primary_textarea.attrs['placeholder'] == "Primary"
    
    secondary_textarea = Textarea(
        placeholder="Secondary",
        cls=combine_classes(textarea, textarea_colors.secondary)
    )
    assert "textarea-secondary" in secondary_textarea.attrs['class']
    assert secondary_textarea.attrs['placeholder'] == "Secondary"
    
    accent_textarea = Textarea(
        placeholder="Accent",
        cls=combine_classes(textarea, textarea_colors.accent)
    )
    assert "textarea-accent" in accent_textarea.attrs['class']
    assert accent_textarea.attrs['placeholder'] == "Accent"
    
    neutral_textarea = Textarea(
        placeholder="Neutral",
        cls=combine_classes(textarea, textarea_colors.neutral)
    )
    assert "textarea-neutral" in neutral_textarea.attrs['class']
    assert neutral_textarea.attrs['placeholder'] == "Neutral"
    
    info_textarea = Textarea(
        placeholder="Info",
        cls=combine_classes(textarea, textarea_colors.info)
    )
    assert "textarea-info" in info_textarea.attrs['class']
    assert info_textarea.attrs['placeholder'] == "Info"
    
    success_textarea = Textarea(
        placeholder="Success",
        cls=combine_classes(textarea, textarea_colors.success)
    )
    assert "textarea-success" in success_textarea.attrs['class']
    assert success_textarea.attrs['placeholder'] == "Success"
    
    warning_textarea = Textarea(
        placeholder="Warning",
        cls=combine_classes(textarea, textarea_colors.warning)
    )
    assert "textarea-warning" in warning_textarea.attrs['class']
    assert warning_textarea.attrs['placeholder'] == "Warning"
    
    error_textarea = Textarea(
        placeholder="Error",
        cls=combine_classes(textarea, textarea_colors.error)
    )
    assert "textarea-error" in error_textarea.attrs['class']
    assert error_textarea.attrs['placeholder'] == "Error"
    
    # Return all color variations
    return Div(
        primary_textarea,
        secondary_textarea,
        accent_textarea,
        neutral_textarea,
        info_textarea,
        success_textarea,
        warning_textarea,
        error_textarea
    )

# Run the tests
test_textarea_colors_fasthtml_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #24309e5c-6cac-4d0c-aa31-d61c153e8fd0
def test_textarea_sizes_fasthtml_examples():
    """Test textarea size variations from daisyUI v5 documentation."""
    from fasthtml.common import Textarea, Div
    
    # Textarea sizes
    xs_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_sizes.xs)
    )
    assert "textarea" in xs_textarea.attrs['class']
    assert "textarea-xs" in xs_textarea.attrs['class']
    assert xs_textarea.attrs['placeholder'] == "Bio"
    
    sm_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_sizes.sm)
    )
    assert "textarea-sm" in sm_textarea.attrs['class']
    
    md_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_sizes.md)
    )
    assert "textarea-md" in md_textarea.attrs['class']
    
    lg_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_sizes.lg)
    )
    assert "textarea-lg" in lg_textarea.attrs['class']
    
    xl_textarea = Textarea(
        placeholder="Bio",
        cls=combine_classes(textarea, textarea_sizes.xl)
    )
    assert "textarea-xl" in xl_textarea.attrs['class']
    
    # Return all size variations
    return Div(
        xs_textarea,
        sm_textarea,
        md_textarea,
        lg_textarea,
        xl_textarea
    )

# Run the tests
test_textarea_sizes_fasthtml_examples()

# %% ../../../nbs/components/data_input/textarea.ipynb #13f9763c-1e45-4ea4-b36b-71b0a0f3d6f9
def test_textarea_disabled_fasthtml_examples():
    """Test disabled textarea from daisyUI v5 documentation."""
    from fasthtml.common import Textarea
    
    # Disabled textarea
    disabled_textarea = Textarea(
        placeholder="Bio",
        cls=str(textarea),
        disabled=True
    )
    
    # Verify structure
    assert disabled_textarea.tag == "textarea"
    assert disabled_textarea.attrs['class'] == "textarea"
    assert disabled_textarea.attrs['placeholder'] == "Bio"
    assert disabled_textarea.attrs['disabled'] == True
    
    return disabled_textarea

# Run the tests
test_textarea_disabled_fasthtml_examples()
