"""Toggle is a checkbox that is styled to look like a switch button."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/data_input/toggle.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/data_input/toggle.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
