"""Radial progress can be used to show the progress of a task or to show the passing of time."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/feedback/radial_progress.ipynb.

# %% auto 0
__all__ = ['radial_progress', 'test_radial_progress_basic_examples']

# %% ../../../nbs/components/feedback/radial_progress.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/feedback/radial_progress.ipynb 5
radial_progress = SingleValueFactory("radial-progress", "Shows a radial progress") # Base radial progress component

# %% ../../../nbs/components/feedback/radial_progress.ipynb 7
def test_radial_progress_basic_examples():
    """Test basic button utilities."""
    # Basic button
    assert str(radial_progress) == "radial-progress"
    
    # Radial progress with modifiers
    assert str(radial_progress.hover) == "hover:radial-progress"
    assert str(radial_progress.md) == "md:radial-progress"
    assert str(radial_progress.dark) == "dark:radial-progress"

# Run the tests
test_radial_progress_basic_examples()
