"""Skeleton is a component that can be used to show a loading state of a component."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/feedback/skeleton.ipynb.

# %% auto 0
__all__ = ['skeleton', 'test_skeleton_basic_examples']

# %% ../../../nbs/components/feedback/skeleton.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/feedback/skeleton.ipynb 5
skeleton = SingleValueFactory("skeleton", "A placeholder div with loading animation") # Base skeleton component

# %% ../../../nbs/components/feedback/skeleton.ipynb 7
def test_skeleton_basic_examples():
    """Test basic skeleton utilities."""
    # Basic skeleton
    assert str(skeleton) == "skeleton"
    
    # Skeleton with modifiers
    assert str(skeleton.hover) == "hover:skeleton"
    assert str(skeleton.md) == "md:skeleton"
    assert str(skeleton.dark) == "dark:skeleton"

# Run the tests
test_skeleton_basic_examples()
