"""Toast is a wrapper to stack elements, positioned on the corner of page."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/feedback/toast.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/feedback/toast.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
