"""Footer can contain logo, copyright notice, and links to other pages."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/layout/footer.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/layout/footer.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
