"""Footer can contain logo, copyright notice, and links to other pages."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/layout/footer.ipynb.

# %% auto 0
__all__ = ['footer', 'footer_title', 'footer_placement', 'footer_directions', 'FooterPlacement', 'FooterDirection',
           'test_footer_basic_examples', 'test_footer_placement_examples', 'test_footer_directions_examples']

# %% ../../../nbs/components/layout/footer.ipynb 3
from enum import Enum
from typing import Optional, Dict, Any, Union
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from cjm_fasthtml_tailwind.builders.scales import SimpleFactory, enums_to_simple_factory

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/layout/footer.ipynb 5
footer = SingleValueFactory("footer", "Base footer component") # Base footer component
footer_title = SingleValueFactory("footer-title", "Title of a footer column") # footer title part

# %% ../../../nbs/components/layout/footer.ipynb 7
class FooterPlacement(str, Enum):
    CENTER = "center"

footer_placement = enums_to_simple_factory(footer, [FooterPlacement], "footer placement (center)") # footer placement

# %% ../../../nbs/components/layout/footer.ipynb 9
class FooterDirection(str, Enum):
    VERTICAL = "vertical"
    HORIZONTAL = "horizontal"

footer_directions = enums_to_simple_factory(footer, [FooterDirection], "footer directions (vertical, horizontal)") # footer directions

# %% ../../../nbs/components/layout/footer.ipynb 11
def test_footer_basic_examples():
    """Test basic footer utilities."""
    # Basic footer
    assert str(footer) == "footer"
    assert str(footer_title) == "footer-title"
    
    # Test with modifiers
    assert str(footer.hover) == "hover:footer"
    assert str(footer.md) == "md:footer"
    assert str(footer.dark) == "dark:footer"

# Run the tests
test_footer_basic_examples()

# %% ../../../nbs/components/layout/footer.ipynb 12
def test_footer_placement_examples():
    """Test footer placement variants."""
    assert str(footer_placement.center) == "footer-center"

# Run the tests
test_footer_placement_examples()

# %% ../../../nbs/components/layout/footer.ipynb 13
def test_footer_directions_examples():
    """Test footer directions variants."""
    assert str(footer_directions.vertical) == "footer-vertical"
    assert str(footer_directions.horizontal) == "footer-horizontal"

# Run the tests
test_footer_directions_examples()
