"""Hero is a component for displaying a large box or image with a title and description."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/layout/hero.ipynb.

# %% auto 0
__all__ = ['hero', 'hero_content', 'hero_overlay', 'test_hero_basic_examples']

# %% ../../../nbs/components/layout/hero.ipynb 3
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/layout/hero.ipynb 5
hero = SingleValueFactory("hero", "Base hero container") # Base hero component
hero_content = SingleValueFactory("hero-content", "Hero content part") # Hero content part
hero_overlay = SingleValueFactory("hero-overlay", "Hero overlay that covers the background image") # Hero overlay part

# %% ../../../nbs/components/layout/hero.ipynb 7
def test_hero_basic_examples():
    """Test basic hero utilities."""
    # Basic hero
    assert str(hero) == "hero"
    assert str(hero_content) == "hero-content"
    assert str(hero_overlay) == "hero-overlay"
    
    # Test with modifiers
    assert str(hero.hover) == "hover:hero"
    assert str(hero.md) == "md:hero"
    assert str(hero.dark) == "dark:hero"

# Run the tests
test_hero_basic_examples()
