"""Join is a container for grouping multiple items, it can be used to group buttons, inputs, etc. Join applies border radius to the first and last item. Join can be used to create a horizontal or vertical list of items."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/layout/join.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/components/layout/join.ipynb 3
from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display
