"""Join is a container for grouping multiple items, it can be used to group buttons, inputs, etc. Join applies border radius to the first and last item. Join can be used to create a horizontal or vertical list of items."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/layout/join.ipynb.

# %% auto 0
__all__ = ['join', 'join_item', 'join_directions', 'JoinDirection', 'test_join_basic_examples', 'test_join_directions_examples']

# %% ../../../nbs/components/layout/join.ipynb 3
from enum import Enum
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from cjm_fasthtml_tailwind.builders.scales import SimpleFactory, enums_to_simple_factory

from fasthtml.common import Div
from fasthtml.jupyter import JupyUvi, HTMX
from ...core.testing import create_test_app, create_test_page, start_test_server
from ...core.themes import DaisyUITheme
from IPython.display import display

# %% ../../../nbs/components/layout/join.ipynb 5
join = SingleValueFactory("join", "Base join component for grouping multiple items") # Base join component
join_item = SingleValueFactory("join-item", "Item inside join. Can be a button, input, etc.") # Join item component

# %% ../../../nbs/components/layout/join.ipynb 7
class JoinDirection(str, Enum):
    VERTICAL = "vertical"
    HORIZONTAL = "horizontal"

join_directions = enums_to_simple_factory(join, [JoinDirection], "join directions (vertical, horizontal)") # join directions

# %% ../../../nbs/components/layout/join.ipynb 9
def test_join_basic_examples():
    """Test basic join utilities."""
    # Basic join
    assert str(join) == "join"
    assert str(join_item) == "join-item"
    
    # Test with modifiers
    assert str(join.hover) == "hover:join"
    assert str(join.md) == "md:join"
    assert str(join.dark) == "dark:join"

    assert str(join_item.hover) == "hover:join-item"
    assert str(join_item.md) == "md:join-item"
    assert str(join_item.dark) == "dark:join-item"

# Run the tests
test_join_basic_examples()

# %% ../../../nbs/components/layout/join.ipynb 10
def test_join_directions_examples():
    """Test join directions variants."""
    assert str(join_directions.vertical) == "join-vertical"
    assert str(join_directions.horizontal) == "join-horizontal"

# Run the tests
test_join_directions_examples()
